// bundle iconify art for the browser. run `pnpm run icons:generate` after edits.
import { readFile, writeFile } from "node:fs/promises";
import { getIconData, iconToSVG } from "@iconify/utils";
import { format, resolveConfig } from "prettier";
import fileIcons from "@iconify-json/file-icons/icons.json" with { type: "json" };
import fluent from "@iconify-json/fluent/icons.json" with { type: "json" };
import gameIcons from "@iconify-json/game-icons/icons.json" with { type: "json" };
import icIcons from "@iconify-json/ic/icons.json" with { type: "json" };
import materialSymbolsLight from "@iconify-json/material-symbols-light/icons.json" with { type: "json" };
import simpleIcons from "@iconify-json/simple-icons/icons.json" with { type: "json" };
import systemUicons from "@iconify-json/system-uicons/icons.json" with { type: "json" };

const OUTPUT_FILE = new URL("../lib/icons-generated.ts", import.meta.url);
const factorySvg = await readFile(
  new URL("../public/factory-logo.svg", import.meta.url),
  "utf8",
);
const factoryPath = factorySvg.match(/<path d="([^"]+)" fill="#FAFAFA"/)?.[1];
if (!factoryPath) throw new Error("factory logo path not found");

const ICON_SETS = {
  "simple-icons": simpleIcons,
  "file-icons": fileIcons,
  "material-symbols-light": materialSymbolsLight,
  ic: icIcons,
  "game-icons": gameIcons,
  fluent,
  "system-uicons": systemUicons,
};

// keys match getTechIcon calls. keep them sorted.
const ICON_SOURCES = {
  algolia: "simple-icons:algolia",
  aws: "simple-icons:amazonwebservices",
  betterauth: "simple-icons:betterauth",
  chain: "system-uicons:chain",
  codex: "simple-icons:openai",
  cursor: "simple-icons:cursor",
  drizzle: "simple-icons:drizzle",
  email: "ic:outline-email",
  excalidraw: "simple-icons:excalidraw",
  express: "simple-icons:express",
  food: "fluent:food-24-regular",
  git: "simple-icons:git",
  github: "simple-icons:github",
  linear: "simple-icons:linear",
  linkedin: "simple-icons:linkedin",
  neon: "material-symbols-light:database-outline",
  nextjs: "file-icons:nextjs",
  notion: "simple-icons:notion",
  obsidian: "simple-icons:obsidian",
  posthog: "simple-icons:posthog",
  postgres: "simple-icons:postgresql",
  python: "simple-icons:python",
  react: "simple-icons:react",
  render: "simple-icons:render",
  resend: "simple-icons:resend",
  sanity: "simple-icons:sanity",
  sentry: "simple-icons:sentry",
  shadcn: "simple-icons:shadcnui",
  slack: "simple-icons:slack",
  stripe: "simple-icons:stripe",
  tailwind: "simple-icons:tailwindcss",
  travel: "game-icons:palm-tree",
  typescript: "simple-icons:typescript",
  vercel: "simple-icons:vercel",
  vite: "simple-icons:vite",
};

// icons without an iconify entry live here.
const CUSTOM_ICONS = {
  factory: {
    body: `<g transform="translate(-94 -94)"><path d="${factoryPath}"/></g>`,
    width: 320,
    height: 320,
  },
  // inngest has no simple-icons entry.
  inngest: {
    body: '<path fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M2 12h4l3-8 4 16 3-8h4"/>',
    width: 24,
    height: 24,
  },
};

function buildIcon(source) {
  const [setName, iconName] = source.split(":");
  const data = getIconData(ICON_SETS[setName], iconName);
  if (!data) {
    throw new Error(`Icon not found: ${source}`);
  }
  const { attributes, body } = iconToSVG(data);
  const [left, top, width, height] = attributes.viewBox.split(" ").map(Number);
  if (left !== 0 || top !== 0) {
    throw new Error(
      `${source} has a non-zero viewBox origin: ${attributes.viewBox}`,
    );
  }
  if (/(?:fill|stroke)="#/.test(body)) {
    throw new Error(
      `${source} has a hard-coded color; expected currentColor artwork`,
    );
  }
  return { body, width, height };
}

const entries = {
  ...Object.fromEntries(
    Object.entries(ICON_SOURCES).map(([key, source]) => [
      key,
      buildIcon(source),
    ]),
  ),
  ...CUSTOM_ICONS,
};

const lines = Object.keys(entries)
  .sort()
  .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(entries[key])},`);

const source = `// generated by scripts/generate-icons.mjs. don't edit this file.
// regenerate with \`pnpm run icons:generate\`.
export interface GeneratedIcon {
  body: string;
  height: number;
  width: number;
}

export const GENERATED_ICONS: Record<string, GeneratedIcon> = {
${lines.join("\n")}
};
`;

const prettierOptions = (await resolveConfig(OUTPUT_FILE.pathname)) ?? {};
await writeFile(
  OUTPUT_FILE,
  await format(source, { ...prettierOptions, parser: "typescript" }),
);
console.log(
  `Wrote ${Object.keys(entries).length} icons to lib/icons-generated.ts`,
);
